### ISSUE TITLE
Verificação de feriados móveis

### ISSUE THREAD

**Issue by Keony1** [paulohenriquesn/eferiado#1]
ex: em 2020 a sexta-feira santa foi dia 10/04, e no ano que vem (2022) vai ser no dia 15/04

[feriado móvel](https://pt.wikipedia.org/wiki/Feriado_m%C3%B3vel)

**Comment by tuliocll** [comment]
uma solução legal para esse problema seria no json de datas, no campo "data", ao invés de uma string, poderia ser um array de string contendo as datas e o ano, faria um filter e um includes.
Isso obviamente para essas datas que "mudam".
Algo como:

`feriados.json`:
```json
"feriados": [
        {
            "nome": "Ano Novo",
            "data": ["10/04/2021", "10/04/2022"]
        }
];
```

`index.js`:
```javascript
 const findHoliday = feriados.filter(x => x.data.includes(date))
```

**Comment by EduardoJM** [comment]
O único lado ruim dessa solução é que vai ter de adicionar todas as datas pra tal feriado no json... ficaria bem limitado no sentido de não poder verificar feriados de outros anos (que não estariam adicionados na lista de datas).

Pra alguns casos, daria pra usar alguns algoritmos, como aqui:
https://pt.wikipedia.org/wiki/Cálculo_da_Páscoa

**Comment by paulohenriquesn** [comment]
Opa galerinha obrigado, estou resolvendo agora mesmo ;) ja esta na verdade resolvido vou só subir.

**Comment by Keony1** [comment]
> O único lado ruim dessa solução é que vai ter de adicionar todas as datas pra tal feriado no json... ficaria bem limitado no sentido de não poder verificar feriados de outros anos (que não estariam adicionados na lista de datas).
> 
> Pra alguns casos, daria pra usar alguns algoritmos, como aqui:
> [https://pt.wikipedia.org/wiki/Cálculo_da_Páscoa](https://pt.wikipedia.org/wiki/C%C3%A1lculo_da_P%C3%A1scoa)

Acho que é o único jeito de resolver de forma dinâmica.
Agora para os feriados que são fixos (dia do trabalho, natal, ano novo) acredito que seria melhor deixar eles em constantes, por ser mais performático do que consultar em um json  (mas isso é história pra outra issue ou pr)

**Comment by tuliocll** [comment]
> O único lado ruim dessa solução é que vai ter de adicionar todas as datas pra tal feriado no json... ficaria bem limitado no sentido de não poder verificar feriados de outros anos (que não estariam adicionados na lista de datas).
> 
> Pra alguns casos, daria pra usar alguns algoritmos, como aqui:
> [https://pt.wikipedia.org/wiki/Cálculo_da_Páscoa](https://pt.wikipedia.org/wiki/C%C3%A1lculo_da_P%C3%A1scoa)

Não tinha pensado dessa forma, excelente! 
@paulohenriquesn a implementação ficou super legal!
