### ISSUE TITLE
Passar Estado como parametro para feriados regionais

### ISSUE THREAD

**Issue by tuliocll** [paulohenriquesn/eferiado#10]
Seria legal ter a possibilidade de passar o estado para retornar apenas feriados regionais de um determinado estado, exemplo:

```javascript
const response = eFeriado('02/07', 'BA');
//  { eFeriadoNacional: false, eFeriadoRegional: true, feriadoNacional: '', feriadosRegionais: [{ nome: 'Independência da Bahia', estado: 'BA' }] }
```

**Comment by rmrantunes** [comment]
Show!!!

**Comment by rmrantunes** [comment]
Nesse caso, eu acho que ficaria melhor passar um objeto como argumento, para que se quiser passar somente o estado e receber todos os feriados de um estado, mas isso mudaria o modelo do objeto retornado, causaria inconsistência, comparado com o que é retornado "atualmente", ver  #9 . Já que se houvesse somente o estado, ele não retornaria a propriedade data que é retornado no PR citado, mas simplesmente um array com somente feriados regionais. Porém, isso que eu digo é levando em consideração se meu PR for aceito, que já há mudanças abruptas no retorno.

```js
const response = eFeriado({ data: '02/07', estado: 'BA' });
```

**Comment by rmrantunes** [comment]
Pensando melhor, minha proposta é que a função que vem do 
```js
 require("eferiado")
```
retornasse um objeto com métodos diferentes, por exemplo, ```getHolidaysByState(estado) || getHolidays(data)```.
O primeiro retornaria somente uma array com feriados regionais, já a segunda retornaria o mesmo que no #9

**Comment by tuliocll** [comment]
> Nesse caso, eu acho que ficaria melhor passar um objeto como argumento, para que se quiser passar somente o estado e receber todos os feriados de um estado, mas isso mudaria o modelo do objeto retornado, causaria inconsistência, comparado com o que é retornado "atualmente", ver #9 . Já que se houvesse somente o estado, ele não retornaria a propriedade data que é retornado no PR citado, mas simplesmente um array com somente feriados regionais. Porém, isso que eu digo é levando em consideração se meu PR for aceito, que já há mudanças abruptas no retorno.
> 
> ```js
> const response = eFeriado({ data: '02/07', estado: 'BA' });
> ```

Acho que essa forma funciona legal, por que poderia buscar só pela data, só pelo estado ou pelos dois, o que acha ?

**Comment by rmrantunes** [comment]
Se pesquisar só pelo estado, a função se tornará inconsistente, pois irá retornar um array com feriados de várias datas do mesmo estado, e não mais um objeto, como [definido](https://github.com/paulohenriquesn/eferiado/blob/main/index.d.ts). O retorno deve ter um padrão. Quem tiver uma ideia ou implementação, seja baseando na minha acima, seja uma nova, pode trazer.

**Comment by rmrantunes** [comment]
O que imagino para o retorno do seria, simplesmente: ```RegionalHoliday[]```
```ts
export interface RegionalHoliday {
    nome: string;
    estado: string;
    data?: string
}
```

**Comment by rmrantunes** [comment]
> Pensando melhor, minha proposta é que a função que vem do
> 
> ```js
>  require("eferiado")
> ```
> 
> retornasse um objeto com métodos diferentes, por exemplo, `getHolidaysByState(estado) || getHolidays(data)`.
> O primeiro retornaria somente uma array com feriados regionais, já a segunda retornaria o mesmo que no #9

Então, reforço minha proposta em fazer 2 funções que lidariam com os diferentes retornos. Se ninguém vier com uma melhor, claro.
