### ISSUE TITLE
As datas estão entrando em conflito. DD/MM e MM/DD 

### ISSUE THREAD

**Issue by rmrantunes** [paulohenriquesn/eferiado#6]
Datas regionais estão entrando em conflito com datas nacionais. Aparentemente, uma é em setembro, a outra em julho.
https://github.com/paulohenriquesn/eferiado/blob/2d08578218e8c95fd52742aab9919fde2e68c2ab/src/feriados.js#L39-L40
https://github.com/paulohenriquesn/eferiado/blob/2d08578218e8c95fd52742aab9919fde2e68c2ab/src/feriados.js#L69

**Comment by paulohenriquesn** [comment]
Opa perfeito issue, sabe me dizer se o seu pr novo já corrige isso ?

**Comment by rmrantunes** [comment]
Não, só percebi depois

**Comment by paulohenriquesn** [comment]
perfeito valeu vou dar merged e dar um fix

**Comment by paulohenriquesn** [comment]
Arrumado fiz um script para remapear e inverter eles.

```js
feriadosRegionais.map((i) => {
let dia = ""
let mes = ""
let memory = i.data.split('/')
mes = memory[0]
dia = memory[1]
i.data = `${dia}/${mes}`;
})
```
